### ISSUE TITLE
Problem at loading DialogSwapper

### ISSUE THREAD

**Issue by bebetoalves** [TypesettingTools/CoffeeFlux-Aegisub-Scripts#3]
Error print: http://i.imgur.com/WKnRbdp.png

**Comment by CoffeeFlux** [comment]
Hey, just got back from vacation - I'll take a look later today.

**Comment by CoffeeFlux** [comment]
Forgot to comment on this, but it's a known upstream bug with DepCtrl. Should be fixed with 0.7. I'll close once that's out and I can verify it's resolved.

**Comment by CoffeeFlux** [comment]
Was fixed at some point randomly, at least on my latest builds.
